import {
  MentorProfile,
  StudentProfile,
  Session,
  CreditTransaction,
  QAQuestion,
  InsightCardData,
} from './types';

export const INITIAL_STUDENTS: StudentProfile[] = [
  {
    id: 's1',
    name: 'Maya Lin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    title: 'CS Junior @ UC Berkeley',
    universityOrCompany: 'UC Berkeley',
    goalStage: 'interviewing',
    careerGoal: 'Software Engineer at Top Tech Firm',
    interests: ['Frontend', 'Distributed Systems', 'System Design', 'Tech Resume'],
    credits: 3.25,
    noShowCount: 0,
    cooldownUntil: null,
    reliabilityScore: 96,
    history: {
      attended: 5,
      noShows: 0,
      totalBooked: 5,
    },
  },
  {
    id: 's2',
    name: 'Alex Rivera',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    title: 'MBA Candidate @ NYU Stern',
    universityOrCompany: 'NYU Stern',
    goalStage: 'exploring',
    careerGoal: 'Product Management in FinTech',
    interests: ['Product Strategy', 'FinTech', 'Agile', 'Resume Glance'],
    credits: 2.0,
    noShowCount: 1,
    cooldownUntil: null,
    reliabilityScore: 88,
    history: {
      attended: 3,
      noShows: 1,
      totalBooked: 4,
    },
  },
  {
    id: 's3',
    name: 'Jordan Chen',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    title: 'Self-taught UX Designer',
    universityOrCompany: 'Career Switcher',
    goalStage: 'early_career',
    careerGoal: 'Product Designer at Growth Startup',
    interests: ['Portfolio Review', 'UX Research', 'Design Systems'],
    credits: 1.0,
    noShowCount: 3,
    cooldownUntil: '2026-08-18T12:00:00Z', // Active cooldown example
    reliabilityScore: 62,
    history: {
      attended: 2,
      noShows: 3,
      totalBooked: 5,
    },
  },
  {
    id: 's4',
    name: 'Priya Sharma',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    title: 'Pre-Med Senior @ Johns Hopkins',
    universityOrCompany: 'Johns Hopkins',
    goalStage: 'exploring',
    careerGoal: 'HealthTech Entrepreneurship & Biotech',
    interests: ['Healthcare', 'MedTech', 'Bioinformatics', 'Quick Career Q'],
    credits: 4.0,
    noShowCount: 0,
    cooldownUntil: null,
    reliabilityScore: 100,
    history: {
      attended: 4,
      noShows: 0,
      totalBooked: 4,
    },
  },
];

export const INITIAL_MENTORS: MentorProfile[] = [
  {
    id: 'm1',
    name: 'Marcus Vance',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    title: 'Staff Software Engineer',
    company: 'Stripe',
    industry: 'Tech',
    expertiseTags: ['Frontend', 'System Design', 'Tech Resume', 'Mock Interview Snippet'],
    bio: 'Ex-Google, 10+ years scaling payment systems. Passionate about helping students break into tier-1 tech engineering roles through targeted 15-min practice.',
    availabilitySlots: [
      { id: 'v1', day: 'Today', time: '3:00 PM' },
      { id: 'v2', day: 'Tomorrow', time: '10:30 AM' },
      { id: 'v3', day: 'Thu, Aug 14', time: '4:15 PM' },
    ],
    reliabilityScore: 98,
    responseTimeMinutes: 12,
    completedSessionsCount: 42,
    history: {
      attended: 42,
      noShows: 1,
      totalBooked: 43,
    },
  },
  {
    id: 'm2',
    name: 'Elena Rostova',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    title: 'Principal Product Designer',
    company: 'Airbnb',
    industry: 'Design',
    expertiseTags: ['Portfolio Review', 'UX Research', 'Design Systems', 'Resume Glance'],
    bio: 'Crafting spatial and digital experiences. I do crisp 15-minute portfolio tear-downs focusing on narrative structure and visual craft.',
    availabilitySlots: [
      { id: 'v4', day: 'Today', time: '5:00 PM' },
      { id: 'v5', day: 'Fri, Aug 15', time: '2:00 PM' },
    ],
    reliabilityScore: 95,
    responseTimeMinutes: 20,
    completedSessionsCount: 31,
    history: {
      attended: 31,
      noShows: 2,
      totalBooked: 33,
    },
  },
  {
    id: 'm3',
    name: 'David Kim',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    title: 'VP of Investment Banking',
    company: 'Goldman Sachs',
    industry: 'Finance',
    expertiseTags: ['FinTech', 'Financial Modeling', 'Interview Prep', 'Quick Career Q'],
    bio: 'Wall Street veteran giving non-traditional students unfiltered clarity on recruiting pathways, networking outreach, and interview questions.',
    availabilitySlots: [
      { id: 'v6', day: 'Tomorrow', time: '8:00 AM' },
      { id: 'v7', day: 'Thu, Aug 14', time: '6:30 PM' },
    ],
    reliabilityScore: 92,
    responseTimeMinutes: 35,
    completedSessionsCount: 28,
    history: {
      attended: 28,
      noShows: 2,
      totalBooked: 30,
    },
  },
  {
    id: 'm4',
    name: 'Dr. Sarah Jenkins',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80',
    title: 'Head of Clinical AI Strategy',
    company: 'Verily Health',
    industry: 'Healthcare',
    expertiseTags: ['Healthcare', 'MedTech', 'Bioinformatics', 'Career Strategy'],
    bio: 'Bridging medicine and data science. Happy to review residency/grad applications, startup ideas, or research pitch decks in fast 15-min calls.',
    availabilitySlots: [
      { id: 'v8', day: 'Wed, Aug 13', time: '1:00 PM' },
      { id: 'v9', day: 'Fri, Aug 15', time: '11:00 AM' },
    ],
    reliabilityScore: 100,
    responseTimeMinutes: 8,
    completedSessionsCount: 19,
    history: {
      attended: 19,
      noShows: 0,
      totalBooked: 19,
    },
  },
  {
    id: 'm5',
    name: 'Tariq Al-Mansoor',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    title: 'Director of Growth Marketing',
    company: 'Duolingo',
    industry: 'Marketing',
    expertiseTags: ['Growth Strategy', 'Brand Marketing', 'Portfolio Review', 'Resume Glance'],
    bio: 'Pioneered viral campaigns and user acquisition funnels. I help early marketers position their unique storytelling edge.',
    availabilitySlots: [
      { id: 'v10', day: 'Today', time: '4:30 PM' },
      { id: 'v11', day: 'Tomorrow', time: '1:15 PM' },
    ],
    reliabilityScore: 90,
    responseTimeMinutes: 25,
    completedSessionsCount: 22,
    history: {
      attended: 22,
      noShows: 2,
      totalBooked: 24,
    },
  },
  {
    id: 'm6',
    name: 'Rachel Sterling',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    title: 'Senior Product Manager',
    company: 'Meta',
    industry: 'Tech',
    expertiseTags: ['Product Strategy', 'Agile', 'Mock Interview Snippet', 'Tech Resume'],
    bio: 'Managing social platform products. Skilled at teaching product sense frameworks, product execution metrics, and cross-functional leadership.',
    availabilitySlots: [
      { id: 'v12', day: 'Thu, Aug 14', time: '2:30 PM' },
      { id: 'v13', day: 'Fri, Aug 15', time: '5:00 PM' },
    ],
    reliabilityScore: 96,
    responseTimeMinutes: 15,
    completedSessionsCount: 38,
    history: {
      attended: 38,
      noShows: 1,
      totalBooked: 39,
    },
  },
];

export const INITIAL_SESSIONS: Session[] = [
  {
    id: 'sess-101',
    studentId: 's1',
    mentorId: 'm1',
    studentName: 'Maya Lin',
    studentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    mentorName: 'Marcus Vance',
    mentorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    mentorTitle: 'Staff Software Engineer',
    mentorCompany: 'Stripe',
    sessionType: 'Mock Interview Snippet',
    topic: 'System Design 15-Min Blitz: Rate Limiter Design',
    scheduledAt: 'Yesterday, 3:00 PM',
    creditCost: 1,
    status: 'Completed',
    rawNotesOrTranscript: `Maya presented a token bucket algorithm implementation for API rate limiting. Marcus highlighted edge cases with multi-threaded environments, redis caching strategies, and recommended keeping time complexity considerations upfront during technical rounds.`,
    digest: {
      summaryHeadline: 'Mastering Token Bucket Rate Limiting for Distributed APIs',
      keyAdvice: [
        'Always clarify multi-datacenter race conditions upfront before choosing in-memory vs Redis counters.',
        'Quantify trade-offs explicitly: Memory overhead vs precise sliding window timestamps.',
        'Use standard RFC HTTP headers (X-RateLimit-Remaining, Retry-After) when answering design questions.'
      ],
      resourcesMentioned: [
        'System Design Interview Vol 1 by Alex Xu',
        'Stripe Engineering Blog: "How we scale API rate limits"'
      ],
      suggestedNextStep: 'Implement a basic Token Bucket middleware in Node/Express and test concurrent requests.',
      generatedAt: '2026-08-10T15:20:00Z',
    },
    isPublicInsight: true,
    createdAt: '2026-08-09T10:00:00Z',
  },
  {
    id: 'sess-102',
    studentId: 's1',
    mentorId: 'm6',
    studentName: 'Maya Lin',
    studentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    mentorName: 'Rachel Sterling',
    mentorAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    mentorTitle: 'Senior Product Manager',
    mentorCompany: 'Meta',
    sessionType: 'Quick Career Q',
    topic: 'Transitioning from SWE intern to Technical Product Management',
    scheduledAt: 'Today, 3:30 PM',
    creditCost: 1,
    status: 'Confirmed',
    isPublicInsight: false,
    createdAt: '2026-08-10T18:00:00Z',
  },
  {
    id: 'sess-103',
    studentId: 's2',
    mentorId: 'm1',
    studentName: 'Alex Rivera',
    studentAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    mentorName: 'Marcus Vance',
    mentorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    mentorTitle: 'Staff Software Engineer',
    mentorCompany: 'Stripe',
    sessionType: 'Resume Glance',
    topic: 'FinTech PM & Technical Resume alignment review',
    scheduledAt: 'Tomorrow, 10:30 AM',
    creditCost: 1,
    status: 'Requested', // Incoming request for mentor Marcus view demo!
    isPublicInsight: false,
    createdAt: '2026-08-11T06:00:00Z',
  },
  {
    id: 'sess-104',
    studentId: 's3',
    mentorId: 'm2',
    studentName: 'Jordan Chen',
    studentAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    mentorName: 'Elena Rostova',
    mentorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    mentorTitle: 'Principal Product Designer',
    mentorCompany: 'Airbnb',
    sessionType: 'Resume Glance',
    topic: 'Portfolio Case Study Review',
    scheduledAt: '3 days ago',
    creditCost: 1,
    status: 'Student_No_Show', // Resolved student no-show example
    isPublicInsight: false,
    createdAt: '2026-08-07T14:00:00Z',
  },
];

export const INITIAL_CREDIT_TRANSACTIONS: CreditTransaction[] = [
  {
    id: 'tx-1',
    userId: 's1',
    userRole: 'student',
    amount: 3.0,
    type: 'Initial Grant',
    description: 'Welcome credit grant upon joining Bridge',
    timestamp: '2026-08-01T09:00:00Z',
  },
  {
    id: 'tx-2',
    userId: 's1',
    userRole: 'student',
    amount: -1.0,
    type: 'Escrow Hold',
    description: 'Held for session sess-101 with Marcus Vance',
    timestamp: '2026-08-09T10:00:00Z',
    sessionId: 'sess-101',
  },
  {
    id: 'tx-3',
    userId: 's1',
    userRole: 'student',
    amount: 1.0,
    type: 'Escrow Refund',
    description: 'Session sess-101 completed successfully',
    timestamp: '2026-08-10T15:00:00Z',
    sessionId: 'sess-101',
  },
  {
    id: 'tx-4',
    userId: 's1',
    userRole: 'student',
    amount: 0.25,
    type: 'Attendance Bonus',
    description: 'Reliable attendee bonus (+0.25 credits) for session sess-101',
    timestamp: '2026-08-10T15:00:00Z',
    sessionId: 'sess-101',
  },
  {
    id: 'tx-5',
    userId: 's1',
    userRole: 'student',
    amount: -1.0,
    type: 'Escrow Hold',
    description: 'Held for session sess-102 with Rachel Sterling',
    timestamp: '2026-08-10T18:00:00Z',
    sessionId: 'sess-102',
  },
  {
    id: 'tx-6',
    userId: 'm1',
    userRole: 'mentor',
    amount: 1.0,
    type: 'Mentor Compensation',
    description: 'Compensation credit earned for completing 15-min session',
    timestamp: '2026-08-10T15:00:00Z',
    sessionId: 'sess-101',
  },
];

export const INITIAL_QA_QUESTIONS: QAQuestion[] = [
  {
    id: 'q-1',
    studentId: 's1',
    studentName: 'Maya Lin',
    studentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    studentGoal: 'CS Junior @ UC Berkeley',
    title: 'How do you structure bullet points on a tech resume when you have no formal engineering internship yet?',
    content: 'I have 2 strong open-source side projects and a teaching assistant role, but no company logo on my resume. How should I phrase my project achievements so recruiters notice engineering rigor?',
    tags: ['Tech Resume', 'Frontend', 'Early Career'],
    upvotes: 18,
    createdAt: '2 days ago',
    answers: [
      {
        id: 'a-1',
        mentorId: 'm1',
        mentorName: 'Marcus Vance',
        mentorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        mentorTitle: 'Staff Software Engineer',
        mentorCompany: 'Stripe',
        content: 'Focus on performance metrics and technical stack decisions! Instead of "Built a React dashboard", write "Architected a React + Vite dashboard processing 1,000+ WebSocket events/sec with under 50ms render latency". Treat your side projects like micro-products.',
        helpfulCount: 14,
        createdAt: '1 day ago',
      },
      {
        id: 'a-2',
        mentorId: 'm6',
        mentorName: 'Rachel Sterling',
        mentorAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
        mentorTitle: 'Senior Product Manager',
        mentorCompany: 'Meta',
        content: 'Highlight user impact or TA mentoring scale! E.g. "Mentored 120+ undergraduates in data structures, raising section average by 12%".',
        isPrivateOffer: true, // Offered 15-min private ask!
        helpfulCount: 6,
        createdAt: '18 hours ago',
      },
    ],
  },
  {
    id: 'q-2',
    studentId: 's2',
    studentName: 'Alex Rivera',
    studentAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    studentGoal: 'MBA Candidate @ NYU Stern',
    title: 'What is the most effective cold outreach message length when requesting a 15-min chat on LinkedIn?',
    content: 'Is 3 paragraphs too long? Should I include my resume right away or wait for them to respond first?',
    tags: ['FinTech', 'Networking', 'Career Strategy'],
    upvotes: 12,
    createdAt: '3 days ago',
    answers: [
      {
        id: 'a-3',
        mentorId: 'm3',
        mentorName: 'David Kim',
        mentorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
        mentorTitle: 'VP of Investment Banking',
        mentorCompany: 'Goldman Sachs',
        content: 'Keep it under 60 words! State who you are, 1 specific piece of their work you admire, and a crisp 15-minute question. Do not attach a resume on first contact — make it low friction to say yes.',
        helpfulCount: 19,
        createdAt: '2 days ago',
      },
    ],
  },
];

export const INITIAL_INSIGHTS: InsightCardData[] = [
  {
    id: 'ins-1',
    sessionId: 'sess-101',
    mentorName: 'Marcus Vance',
    mentorTitle: 'Staff Software Engineer',
    mentorCompany: 'Stripe',
    mentorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    studentName: 'Maya Lin',
    studentGoal: 'CS Junior @ UC Berkeley',
    industry: 'Tech',
    topic: 'System Design 15-Min Blitz: Rate Limiter Design',
    sessionType: 'Mock Interview Snippet',
    digest: {
      summaryHeadline: 'Mastering Token Bucket Rate Limiting for Distributed APIs',
      keyAdvice: [
        'Always clarify multi-datacenter race conditions upfront before choosing in-memory vs Redis counters.',
        'Quantify trade-offs explicitly: Memory overhead vs precise sliding window timestamps.',
        'Use standard RFC HTTP headers (X-RateLimit-Remaining, Retry-After) when answering design questions.'
      ],
      resourcesMentioned: [
        'System Design Interview Vol 1 by Alex Xu',
        'Stripe Engineering Blog: "How we scale API rate limits"'
      ],
      suggestedNextStep: 'Implement a basic Token Bucket middleware in Node/Express and test concurrent requests.',
      generatedAt: '2026-08-10T15:20:00Z',
    },
    likesCount: 24,
    createdAt: '2026-08-10T15:20:00Z',
  },
  {
    id: 'ins-2',
    sessionId: 'sess-legacy-99',
    mentorName: 'Elena Rostova',
    mentorTitle: 'Principal Product Designer',
    mentorCompany: 'Airbnb',
    mentorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    studentName: 'Samira Patel',
    studentGoal: 'Product Design Switcher',
    industry: 'Design',
    topic: '15-Min Portfolio Tear-down: UX Case Study Structure',
    sessionType: 'Resume Glance',
    digest: {
      summaryHeadline: '3 Essential Slides for Every Junior UX Portfolio Case Study',
      keyAdvice: [
        'Lead with the core problem statement & business metric before showing wireframes.',
        'Show 2 rejected design iterations to demonstrate trade-off reasoning.',
        'Include a 30-second loom screen recording of the final prototype at the top.'
      ],
      resourcesMentioned: [
        'Figma Design Tokens Guide',
        'Nielsen Norman Group UX Heuristics Cheat Sheet'
      ],
      suggestedNextStep: 'Re-order case study sections to put the interactive prototype within the first scroll view.',
      generatedAt: '2026-08-08T11:00:00Z',
    },
    likesCount: 38,
    createdAt: '2026-08-08T11:00:00Z',
  },
];
